#!/bin/sh

### MUST REMEMBER THIS!!!!
ntoys=3000
nevts=21
sample=kScalar_fa3p5
params=kAllFree
bkg=true
iter=0
pure=false

# The batch job directory (will vanish after job end):
curdir=`pwd`
workdir=/afs/cern.ch/user/s/sbologne/workspace/multidimFit_addBackg/ZZMatrixElement/snowmass2013/test

# printing
echo what is the workdir...$workdir
echo what is the curdir....$curdir

source /afs/cern.ch/sw/lcg/app/releases/ROOT/5.28.00/slc4_amd64_gcc34/root/bin/thisroot.sh

# tells the scheduler to put all output files into the directory where
# we spawned from
cd $workdir

echo "ntoys: " $ntoys
echo "nevts: " $nevts
echo "sample: " $sample
echo "params: " $params
echo "bakcground: " $bkg
echo "iteration: " $iter
echo "pure: " $pure


root -l -n -b -q loadLib.C "embeddedToys.C(${nevts},${ntoys},${pure},${sample},${params},${bkg},${iter})"

