#!/bin/sh
# !!!!!!!!!! NOTE !!!!!!!!!!!!!!!!!!!!
# all lines that begin with a pound sign(#) and PBS
# are directive lines passed to the qsub command automatically.
# DO NOT REMOVE THE POUND SIGN! A PBS line without a pound sign is
# technically a syntax error and will cause the PBS script to not work 
# properly!  Lines that begin with #PBS are NOT COMMENTS! They are DIRECTIVE
# lines and WILL be parsed by the scheduler unless REMOVED!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# 
# see http://www.clusterresources.com/wiki/doku.php?id=torque:commands:qsub
# for more job tunables and qsub options.  Optionally, check the man page 
# for qsub.
#
# tells the scheduler what queue to submit the job to
#PBS -q batch
# requests the max wall time for this job
#PBS -l walltime=2000:00
#
#
# "nodes" in this respect is actually a 'tuning' option for the job as well as 
# how you specify how many processors you need to run the job.  It's a very tricky 
# setting to understand exactly how it will effect your job's 'runability.'
#
#    -l nodes=80  yields 80 processors and lets the scheduler decide where to run 
#                 the processes.  This is your best bet for getting your job out of idle
#                 in the fastest possible way as long as you don't need a large number
#                 of processors.  NOTE: you can only specify up to the maximum
#                 current count of nodes on the cluster.
#
#    -l nodes=10:ppn=8  still yields 80 processors but specifies that the scheduler
#                       should wait until it can schedule the processes on exactly
#                       10 nodes at 8 processors per node.
#
#    -l nodes=40:ppn=2 still yields 80 processors but spreads out the processes across 
#                      40 nodes at 2 processors per node instead.  This might fit better
#                      if there are a lot of busy hosts with only 2 or so processors idle.
#
#PBS -l nodes=1:ppn=1
# !!!!!!!!!!!!!!! NOTE !!!!!!!!!!!!!!!!!!
# The above PBS LINE is requesting 80 processors.  To disable this, change the node count
# or DELETE the line from the file.
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# this specifies no stderr/stdout merging should be done
#PBS -j n
# tells the scheduler that we want email when the job is 
# aborted and when the job terminates normally.
#PBS -m n 
# send an email to nobody@somewhere.com with job status changes
# MAKE SURE YOU CHANGE THIS LINE OR REMOVE IT!!
#PBS -M whitbeck@pha.jhu.edu
# get output
# !!!!!!!!!!!!!!!! NOTE !!!!!!!!!!!!!!!!!
# path of output file
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#PBS -o /home/whitbeck/CMMSW_2_2_11/src/HiggsAnalysis/HiggsToZZ4Leptons/test/PBSoutput.txt

### MUST REMEMBER THIS!!!!

# The batch job directory (will vanish after job end):
set curdir = `pwd`

# tells the scheduler to put all output files into the directory where
# we spawned from
cd $PBS_O_WORKDIR

# printing
echo what is the workdir...$PBS_O_WORKDIR
echo what is the curdir....$curdir

.//home/whitbeck/4lHelicity/generatorJHU/graviton/graviton Collider=1 Process=0 OffHZZ=011 VegasNc1=500 PChannel=0 DecayMode=0 DataFile=Batch

# shell based output redirection using < > will probably not work consistently.
# I've tested it extensively, and gotten mixed results with it on a consistent 
# basis.
# 
# For output, it is best to let the scheduler gather it and place it in 
# the directory when it's done.  Or, if your program has a way to specify
# an output file, that would be good as well.
#
#
#
