/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSPINZERO_KDINT_ZH
#define ROOSPINZERO_KDINT_ZH

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

 
class RooSpinZero_KDInt_ZH : public RooAbsPdf {
public:
  RooSpinZero_KDInt_ZH() {} ; 
  RooSpinZero_KDInt_ZH(const char *name, const char *title,
		    RooAbsReal& _kd,
		    RooAbsReal& _kdint,
		    RooAbsReal& _fa3,
 		    vector<TH2F*>& _histos,
		    bool  _withAcc);
		    
  RooSpinZero_KDInt_ZH(const RooSpinZero_KDInt_ZH& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSpinZero_KDInt_ZH(*this,newname); }
  inline virtual ~RooSpinZero_KDInt_ZH() { }
  
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
  
	
protected:

  RooRealProxy kd ;
  RooRealProxy kdint ;
  RooRealProxy fa3 ;
  vector<TH2F*> histos;
  bool withAcc;
  
    
  Double_t evaluate() const ;

private:

  ClassDef(RooSpinZero_KDInt_ZH,1) // Your description goes here...
};
 
#endif
